name: Test and Build Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: echo "Installing dependencies..."
        run: npm ci
        
      - name: Run lint
        run: echo "Running lint..."
        run: npm run lint

      - name: Run test
        run: echo "Running test..."
        run: npm test

      - name: Run Build
        run: echo "Building the code..."
        run: npm run build
        
